describe("Entity", function()
  describe("has defaults", function()
    it("like x and y set in constructor.", function()
      local entity = require 'Entity':new(20, 20)
      assert.Equals(20, entity.x)
      assert.Equals(20, entity.y)
    end)
    it("and all flags set to false", function()
      local entity = require 'Entity':new(20, 20)
      assert.False(entity.moveLeft)
      assert.False(entity.moveRight)
      assert.False(entity.moveUp)
      assert.False(entity.moveDown)
    end)
  end)
  describe("has an update method", function()
    it("decreases x when moveLeft is true", function()
      local entity = require 'Entity':new(20, 20)
      entity.moveLeft = true
      entity:update(.1)
      assert.are.equal(18, entity.x)
    end)
    it("increases x when moveRight is true", function()
      local entity = require 'Entity':new(20, 20)
      entity.moveRight = true
      entity:update(.1)
      assert.are.equal(22, entity.x)
    end)
    it("decreases y when moveUp is true", function()
      local entity = require 'Entity':new(20, 20)
      entity.moveUp = true
      entity:update(.1)
      assert.are.equal(18, entity.y)
    end)
    it("increases y when moveDown is true", function()
      local entity = require 'Entity':new(20, 20)
      entity.moveDown = true
      entity:update(.1)
      assert.are.equal(22, entity.y)
    end)
  end)
end)